### ISSUE TITLE
Monjaro arm raspberry pi4 problem

### ISSUE THREAD

**Issue by Slavajun1417** [Jack477/CommanderPi#50]
I install thinter(tk in arch linux), but have a problem
Traceback (most recent call last):
  File "/home/heeloff/CommanderPi/src/main.py", line 9, in <module>
    import gui as g
  File "/home/heeloff/CommanderPi/src/gui.py", line 4, in <module>
    import resources as rs
  File "/home/heeloff/CommanderPi/src/resources.py", line 16, in <module>
    home_path = sys.argv[1]
NameError: name 'sys' is not defined

**Comment by memidhun** [comment]
Same problem for me
